---
image: docker:git
services:
  - docker:dind
stages:
  - test

before_script:
  - pip3 install virtualenv
  - virtualenv virtenv
  - source virtenv/bin/activate
  - pip3 install requirements.txt

role-test-certbot:
  image: python:3
  stage: test
  tags:
    - docker
  script:
    - python -V
    - ansible --version
    - molecule --version
    - pushd roles/certbot
    - molecule test

role-test-common:
  image: python:3
  stage: test
  tags:
    - docker
  script:
    - python -V
    - ansible --version
    - molecule --version
    - pushd roles/common
    - molecule test

role-test-plex:
  image: python:3
  stage: test
  tags:
    - docker
  script:
    - python -V
    - ansible --version
    - molecule --version
    - pushd roles/plex
    - molecule test