---
image: docker:git
services:
  - docker:dind
stages:
  - test

role-test-certbot:
  image: python:3
  stage: test
  tags:
    - docker
  script:
    - apt-get install -y python-pip libssl-dev 
    - pip3 install ansible docker molecule
    - docker -v
    - python -V
    - ansible --version
    - molecule --version
    - pushd roles/certbot
    - molecule test

role-test-common:
  image: python:3
  stage: test
  tags:
    - docker
  script:
    - apt-get install -y python-pip libssl-dev 
    - pip3 install ansible docker molecule
    - docker -v
    - python -V
    - ansible --version
    - molecule --version
    - pushd roles/common
    - molecule test

role-test-plex:
  image: python:3
  stage: test
  tags:
    - docker
  script:
    - apt-get install -y python-pip libssl-dev 
    - pip3 install ansible docker molecule
    - docker -v
    - python -V
    - ansible --version
    - molecule --version
    - pushd roles/plex