---
image: python:3
stages:
  - test

before_script:
  - pip3 install virtualenv
  - virtualenv virtenv
  - source virtenv/bin/activate

role-test-certbot:
  stage: test
  tags:
    - docker
  script:
    - pip3 install ansible molecule docker
    - python -V
    - ansible --version
    - molecule --version
    - pushd roles/certbot
    - molecule test

role-test-common:
  stage: test
  tags:
    - docker
  script:
    - pip3 install ansible molecule docker
    - python -V
    - ansible --version
    - molecule --version
    - pushd roles/common
    - molecule test

role-test-docker:
  stage: test
  tags:
    - docker
  script:
    - pip3 install ansible molecule docker
    - python -V
    - ansible --version
    - molecule --version
    - pushd roles/docker
    - molecule test

role-test-plex:
  stage: test
  tags:
    - docker
  script:
    - pip3 install ansible molecule docker
    - python -V
    - ansible --version
    - molecule --version
    - pushd roles/plex