---
image: docker:dind
services:
  - docker:dind

stages:
  - test

role-test-certbot:
  image: retr0h/molecule
  stage: test
  tags:
    - docker
  script:
    - docker -v
    - python -V
    - ansible --version
    - molecule --version
    - pushd roles/certbot
    - molecule --debug test
    - popd

role-test-common:
  image: retr0h/molecule
  stage: test
  tags:
    - docker
  script:
    - docker -v
    - python -V
    - ansible --version
    - molecule --version
    - pushd roles/common
    - molecule --debug test
    - popd

role-test-plex:
  image: retr0h/molecule
  stage: test
  tags:
    - docker
  script:
    - docker -v
    - python -V
    - ansible --version
    - molecule --version
    - pushd roles/plex
    - molecule --debug test
    - popd
