---
- name: NGINX Docs VM
  hosts: localhost
  user: ansible
  become: true

  pre_tasks:
    - name: Install ansible role dependencies via Galaxy
      local_action: command ansible-galaxy install -r requirements.yml -p roles/

  roles:
    - { role: common }
