---
- src: https://github.com/jhughes01/ansible-role-common
  version: master

- src: https://github.com/jhughes01/ansible-role-certbot
  version: master

- src: https://github.com/jhughes01/ansible-role-plex
  version: master

- src: https://github.com/jhughes01/ansible-role-firewalld
  version: master

