---
- name: Install certbot's required packages
  import_tasks: packages.yaml

- name: Check if there is an existing certificate
  stat:
    path: /etc/letsencrypt/live/jhcloud.io/fullchain.pem
  register: stat_result

- name: Get certificate expiration date
  command: openssl x509 -checkend 172800 -noout -in /etc/letsencrypt/live/jhcloud.io/fullchain.pem
  register: cert_check
  changed_when: cert_check.rc != 0
  failed_when: cert_check.stdout_lines|length > 0

- name: Create / renew letsencrypt certificate
  import_tasks: create-certificate.yaml
  when: cert_check.rc != 0
