---
- name: Install certbot's required packages
  import_tasks: packages.yaml

- name: Get certificate expiration date
  openssl_certificate:
    path: /etc/letsencrypt/live/jhcloud.io/fullchain.pem
    provider: assertonly
    valid_in: 86400
    register: 

- name: Create / renew letsencrypt certificate
  shell: "{{certbot_command}}"
  environment:
    AWS_ACCESS_KEY_ID: "{{certbot_AWS_ACCESS_KEY}}"
    AWS_SECRET_ACCESS_KEY: "{{certbot_AWS_SECRET_KEY}}"
