---
- name: Install certbot's required packages
  import_tasks: packages.yaml

- name: Check if there is an existing certificate
  stat:
    path: /etc/letsencrypt/live/jhcloud.io/fullchain.pem
  register: stat_result

- name: Get certificate expiration date
  openssl_certificate:
    path: /etc/letsencrypt/live/jhcloud.io/fullchain.pem
    provider: assertonly
    valid_in: 86400
    register: certificate_expiry
    msg: certificate_expiry
  when: stat_result.stat.exists == true

- name: Create / renew letsencrypt certificate
  import_tasks: create-certificate.yaml
  when: stat_result.stat.exists == false
