---
- name: Add EPEL repository
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
    gpgcheck: yes

- name: Install common packages
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - git
      - bind-utils
